// <auto-generated />
using Bkl.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bkl.Models.LocalContext
{
    [DbContext(typeof(BklLocalDbContext))]
    [Migration("20221020090823_YoloSqlInit")]
    partial class YoloSqlInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("Bkl.Models.LocalContext.BklLocalYoloDataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPoints")
                        .HasColumnType("TEXT");

                    b.Property<int>("RectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoloPoints")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BklLocalYoloDataSet");
                });

            modelBuilder.Entity("Bkl.Models.LocalContext.BklLocalYoloPath", b =>
                {
                    b.Property<string>("DirName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassStatistic")
                        .HasColumnType("TEXT");

                    b.Property<string>("YoloSetting")
                        .HasColumnType("TEXT");

                    b.HasKey("DirName");

                    b.ToTable("BklLocalYoloPath");
                });
#pragma warning restore 612, 618
        }
    }
}
